"""remove password

Revision ID: 778d6aa05318
Revises: 6ccd537ba27e
Create Date: 2023-02-13 10:58:54.485266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778d6aa05318'
down_revision = '6ccd537ba27e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emote', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('emote', 'image')
    # ### end Alembic commands ###
