"""empty message

Revision ID: a5e2e3e88abd
Revises: 6ccd537ba27e
Create Date: 2023-02-05 14:11:49.736501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e2e3e88abd'
down_revision = '6ccd537ba27e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
