"""Remove large binary from emote model, add object_name

Revision ID: be1bc414365a
Revises: 5d297d312071
Create Date: 2023-02-16 00:09:43.229611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be1bc414365a'
down_revision = '5d297d312071'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emote', sa.Column('object_name', sa.String(), nullable=True))
    op.drop_column('emote', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emote', sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('emote', 'object_name')
    # ### end Alembic commands ###
