"""empty message

Revision ID: d386c84f76ee
Revises: be1bc414365a
Create Date: 2023-02-19 19:22:54.391213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd386c84f76ee'
down_revision = 'be1bc414365a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emote', sa.Column('command', sa.String(length=15), nullable=False))
    op.create_unique_constraint(None, 'emote', ['command'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emote', type_='unique')
    op.drop_column('emote', 'command')
    # ### end Alembic commands ###
